name: Just Sip iOS Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Just Sip
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Just Sip
        run: |
          xcodebuild \
            -project "Just Sip.xcodeproj" \
            -scheme "Just Sip" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            CODE_SIGNING_ALLOWED=NO \
            build
